### ISSUE TITLE
Undesirable side-effect of ActionController::Base#inspect with decent_exposure 

### ISSUE THREAD

**Issue by andydust** [hashrocket/decent_exposure#127] opened 2015-07-28 09:51 UTC
I noticed an issue where my http requests were hanging for a long time when an unrelated exception occurred somewhere in the stack. I found the cause to be a select all query was being run against a table with many many rows.

Object#inspect will recursively call #inspect on instance variables, including decent exposure's @_resources in the case of an ActionController::Base class, which occurs during Rails's controller action exception handling. This can have undesirable effects when combined with single/plural ancestor style exposures as demonstrated in this gist: https://gist.github.com/andydust/b945c80737e082716f3b

One solution could be to create a custom hashy class for @_resources with its own inspect implementation - happy to have a go..

**Comment by gtd** [comment] 2016-01-05 21:21
@mattpolito is there a reason you closed this issue?  This just bit us in production where we had a simple nil reference error.  Instead of receiving an exception notification, instead the request hangs, and the memory usage explodes.  Within seconds of this simple nil reference the worker has allocated an additional gigabyte of RAM.  Fortunately we have monit there to kill the worker before it consumes all swap and crashes the physical machine, but there is no forensic evidence of the actual error since it starts looping before we get the reports.

Here are some graphs to show how serious this issue actually is in production:

![grafana](https://cloud.githubusercontent.com/assets/5603/12127961/1c96e6b2-b3af-11e5-87d0-c4d8e9d97dc0.png)
![newrelic](https://cloud.githubusercontent.com/assets/5603/12127962/1cb31c60-b3af-11e5-8f16-de618a5c5a3a.png)

**Comment by hashrocketeer** [comment] 2016-01-28 22:22
Thanks for letting us know about this issue and for the detailed report! We just tried reproducing this error locally with the latest version of decent_exposure (v2.3.3) and Rails 4.2.4 using code identical to your gist. We pushed the code to github: https://github.com/hashrocketeer/decent_exposure_test

Here is the output of our test:

```
Started GET "/?id=1" for ::1 at 2016-01-28 16:13:59 -0600
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by PostsController#index as HTML
  Parameters: {"id"=>"1"}
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT 1  [["id", 1]]
#<Post id: 1, name: "andre">
Completed 500 Internal Server Error in 20ms (ActiveRecord: 0.5ms)

RuntimeError (hi):
  app/controllers/posts_controller.rb:7:in `index'


  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.5ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.4ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (66.9ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (66.0ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/dev/.rvm/gems/ruby-2.2.3/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (136.9ms)
```

Please let us know if you can still reproduce the issue or if we missed a setup step.

**Comment by andydust** [comment] 2016-02-02 00:52
Apologies for the inaccurate gist I originally posted. I did some more investigation and it appears this problem occurs specifically with the handling of NameError exceptions. I was able to reproduce the issue in a fork of your repo: https://github.com/andydust/decent_exposure_test/commit/491d36d7e08379c7c3b1d74dd8790f00f49e558a

Here's the output
```
Started GET "/" for ::1 at 2016-02-01 16:35:26 -0800
Processing by PostsController#index as HTML
#<Post id: nil, name: nil>
  Post Load (2.3ms)  SELECT "posts".* FROM "posts"
Completed 500 Internal Server Error in 27ms (ActiveRecord: 0.4ms)

NameError (undefined local variable or method `a_type_or_such_that_causes_a_NameError' for #<PostsController:0x007f83a69108f8>):
  app/controllers/posts_controller.rb:7:in `index'


  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.7ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (55.5ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (1.1ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (61.6ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/andy/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (143.0ms)
```

It appears Rails used to have a similar issue with the recursive `#inspect` calls:
http://stackoverflow.com/questions/10716006/rails-exception-in-controller-executes-querying-instance-variables
https://github.com/rails/rails/commit/c479034baa5c293faeb5cf1fb7658b2b614e4ec2

Could `@_resources` become a custom class with it's own `inspect` implementation?
https://github.com/hashrocket/decent_exposure/blob/master/lib/decent_exposure/expose.rb#L11-L13

**Comment by mattpolito** [comment] 2016-09-01 13:58
Closing post as v3.0 is a different codebase

**Closed by mattpolito** 2016-09-01 13:58 UTC
